from count_nomenclature import regexp_config


def get_million_list(million):
    row = million[regexp_config.row_letter]
    number = int(million[regexp_config.column_number])
    nomenclatures_list = []
    if row == 'A' and number == 1:
        nomenclatures_list.append('B' + '-' + '60')
        nomenclatures_list.append('B' + '-' + '1')
        nomenclatures_list.append('B' + '-' + '2')
        nomenclatures_list.append('A' + '-' + '60')
        nomenclatures_list.append(row + '-' + f'{number}')
        nomenclatures_list.append('A' + '-' + '2')
        nomenclatures_list.append('A\'' + '-' + '60')
        nomenclatures_list.append('A\'' + '-' + '1')
        nomenclatures_list.append('A\'' + '-' + '2')
    elif row == 'A' and number == 60:
        nomenclatures_list.append('B' + '-' + '59')
        nomenclatures_list.append('B' + '-' + '60')
        nomenclatures_list.append('B' + '-' + '1')
        nomenclatures_list.append('A' + '-' + '59')
        nomenclatures_list.append(row + '-' + f'{number}')
        nomenclatures_list.append('A' + '-' + '1')
        nomenclatures_list.append('A\'' + '-' + '59')
        nomenclatures_list.append('A\'' + '-' + '60')
        nomenclatures_list.append('A\'' + '-' + '1')
    elif row == 'V' and number == 1:
        nomenclatures_list.append('W' + '-' + '60')
        nomenclatures_list.append('W' + '-' + '1')
        nomenclatures_list.append('W' + '-' + '2')
        nomenclatures_list.append('V' + '-' + '60')
        nomenclatures_list.append(row + '-' + f'{number}')
        nomenclatures_list.append('V' + '-' + '2')
        nomenclatures_list.append('U' + '-' + '60')
        nomenclatures_list.append('U' + '-' + '1')
        nomenclatures_list.append('U' + '-' + '2')
    elif row == 'V' and number == 60:
        nomenclatures_list.append('W' + '-' + '59')
        nomenclatures_list.append('W' + '-' + '60')
        nomenclatures_list.append('W' + '-' + '1')
        nomenclatures_list.append('V' + '-' + '59')
        nomenclatures_list.append(row + '-' + f'{number}')
        nomenclatures_list.append('V' + '-' + '1')
        nomenclatures_list.append('U' + '-' + '59')
        nomenclatures_list.append('U' + '-' + '60')
        nomenclatures_list.append('U' + '-' + '1')
    elif number == 1:
        nomenclatures_list.append(f'{chr(ord(row) + 1)}' + '-' + '60')
        nomenclatures_list.append(f'{chr(ord(row) + 1)}' + '-' + f'{number}')
        nomenclatures_list.append(f'{chr(ord(row) + 1)}' + '-' + f'{number + 1}')
        nomenclatures_list.append(f'{chr(ord(row))}' + '-' + '60')
        nomenclatures_list.append(f'{chr(ord(row))}' + '-' + f'{number}')
        nomenclatures_list.append(f'{chr(ord(row))}' + '-' + f'{number + 1}')
        nomenclatures_list.append(f'{chr(ord(row) - 1)}' + '-' + '60')
        nomenclatures_list.append(f'{chr(ord(row) - 1)}' + '-' + f'{number}')
        nomenclatures_list.append(f'{chr(ord(row) - 1)}' + '-' + f'{number + 1}')
    elif number == 60:
        nomenclatures_list.append(f'{chr(ord(row) + 1)}' + '-' + f'{number - 1}')
        nomenclatures_list.append(f'{chr(ord(row) + 1)}' + '-' + f'{number}')
        nomenclatures_list.append(f'{chr(ord(row) + 1)}' + '-' + '1')
        nomenclatures_list.append(f'{chr(ord(row))}' + '-' + f'{number - 1}')
        nomenclatures_list.append(f'{chr(ord(row))}' + '-' + f'{number}')
        nomenclatures_list.append(f'{chr(ord(row))}' + '-' + '1')
        nomenclatures_list.append(f'{chr(ord(row) - 1)}' + '-' + f'{number - 1}')
        nomenclatures_list.append(f'{chr(ord(row) - 1)}' + '-' + f'{number}')
        nomenclatures_list.append(f'{chr(ord(row) - 1)}' + '-' + '1')
    elif row == 'A':
        nomenclatures_list.append('B' + '-' + f'{number - 1}')
        nomenclatures_list.append('B' + '-' + f'{number}')
        nomenclatures_list.append('B' + '-' + f'{number + 1}')
        nomenclatures_list.append('A' + '-' + f'{number - 1}')
        nomenclatures_list.append('A' + '-' + f'{number}')
        nomenclatures_list.append('A' + '-' + f'{number + 1}')
        nomenclatures_list.append('A\'' + '-' + f'{number - 1}')
        nomenclatures_list.append('A\'' + '-' + f'{number}')
        nomenclatures_list.append('A\'' + '-' + f'{number + 1}')
    elif row == 'V':
        nomenclatures_list.append('W' + '-' + f'{number - 1}')
        nomenclatures_list.append('W' + '-' + f'{number}')
        nomenclatures_list.append('W' + '-' + f'{number + 1}')
        nomenclatures_list.append('V' + '-' + f'{number - 1}')
        nomenclatures_list.append('V' + '-' + f'{number}')
        nomenclatures_list.append('V' + '-' + f'{number + 1}')
        nomenclatures_list.append('U' + '-' + f'{number - 1}')
        nomenclatures_list.append('U' + '-' + f'{number}')
        nomenclatures_list.append('U' + '-' + f'{number + 1}')
    else:
        nomenclatures_list.append(f'{chr(ord(row) + 1)}' + '-' + f'{number - 1}')
        nomenclatures_list.append(f'{chr(ord(row) + 1)}' + '-' + f'{number}')
        nomenclatures_list.append(f'{chr(ord(row) + 1)}' + '-' + f'{number + 1}')
        nomenclatures_list.append(f'{chr(ord(row))}' + '-' + f'{number - 1}')
        nomenclatures_list.append(f'{chr(ord(row))}' + '-' + f'{number}')
        nomenclatures_list.append(f'{chr(ord(row))}' + '-' + f'{number + 1}')
        nomenclatures_list.append(f'{chr(ord(row) - 1)}' + '-' + f'{number - 1}')
        nomenclatures_list.append(f'{chr(ord(row) - 1)}' + '-' + f'{number}')
        nomenclatures_list.append(f'{chr(ord(row) - 1)}' + '-' + f'{number + 1}')
    return nomenclatures_list
